### ISSUE TITLE
 Fix/Verify any warnings and errors in current ICARUS CI tests

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/sbnci#14]
Check thresholds/etc.

Should be done ahead of 13 Aug release.

This may be more appropriate to an icaruscode issues/PR: link here and close this as needed.

**Comment by wesketchum** [comment]
(assigning @rennney , who I think is tracking these things, but please reassign as necessary)

**Comment by rennney** [comment]
icaruscode#232  calibration is done, made some fixes for c7. If something changes with the Friday release might need to update it

**Comment by wesketchum** [comment]
Wonderful!! I'm closing this then, and we can make new issues as needed.
