### ISSUE TITLE
Implement first round of ICARUS validation tests

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/sbnci#15]
Targetting 13 Aug production.

Assigning to @rennney who I think is tracking these things: please reassign as appropriate (and thanks in advance!)

May be more appropriate for icaruscode release: if so link issues/PRs here and can close this if needed.

**Comment by wesketchum** [comment]
I think @rennney was focused on the CI tests, but are we still awaiting larger validation tests? Pushing this to 'Oct' release deliverables for now. We should close if we are reasonably satisfied with what we have for a first round.

**Comment by rennney** [comment]
Hi @wesketchum, I've started working on it, but it will take some time to finish.
