### ISSUE TITLE
missing expert input to validation

### ISSUE THREAD

**Issue by chilge** [SBNSoftware/sbnci#21]
With high-level workflows, fully developed for SBND TPC reco, in place for the TPC reco, TPC sim/cal, CRT sim/reco and PDS sim/reco groups, it is time to hand the workflows over to the physics WGs.

As a first step, developers should port any existing validation analysis modules over to sbnci.

**Comment by chilge** [comment]
Big thanks to @PetrilloAtWork and @fjnicolas for providing expert input for the PDS sim/reco group!

**Comment by wesketchum** [comment]
@chilge reason to keep this open? May be good to close and assign more specific needs in issues if needed.
