### ISSUE TITLE
make sbnci a UPS package

### ISSUE THREAD

**Issue by chilge** [SBNSoftware/sbnci#28]
Up to now, `sbnci` has been primarily used in a development mode. This is likely to remain the case for the near future. However, as validation workflows mature, it will become unnecessary to clone and build `sbnci` locally. A developer working on `sbncode`/`icaruscode` will submit a PR and link some validation results. The validation step should be made as easy as possible to execute. A user should be able to just run `setup sbnci ...` and run some shell script to run the validation tests, two commands in total.

If we are to make `sbnci` a UPS package, we will need to assign sbnci to a release manager. Is this something for the SBN RM group @miquelnebot ?

**Comment by henrylay97** [comment]
Just to drop my two pennies worth. I fully agree it would be useful to have `sbnci` as a UPS product so this would be a great development. 

However, on your point about triggering the validation, this can already be done by running `setup lar_ci` and then using the `trigger` command. I agree that a shell script for some of the more common uses of `trigger` would be very helpful!

**Comment by vitodb** [comment]
In order to allow users to test their PR, we need also to figure out which repos we need to support.
For example the standard SBND CI Validation workflow allows to test `sbndcode sbndutil sbnci` out ot the box, but eventually we would like to enable support for more repos.
On this purpose I'm working on a CI feature that allows users to enable more repos through the `trigger` command line option.

**Comment by chilge** [comment]
thanks for point that out @henrylay97 . to your point @vitodb , we probably need to support the icarus specific equivalents of `sbndcode` and `sbndutil` right?

**Comment by vitodb** [comment]
> to your point @vitodb , we probably need to support the icarus specific equivalents of `sbndcode` and `sbndutil` right?

Right, the equivalent of those packages, and eventually more, if needed.

**Comment by chilge** [comment]
aside from the CI feature you mentioned, are there any other missing pieces?

**Comment by vitodb** [comment]
To get started we need to include the `CI_VALIDATION_ICARUS` workflow to the list of available ICARUS CI workflows, then the actual (or at least a template) for the physics CI validation workflow.
All those components will be part of `lar_ci`.

**Comment by wesketchum** [comment]
Status on this? Think we're ~done and passing to @miquelnebot soon?

**Comment by chilge** [comment]
Still working to get the Jenkins project running. SciSoft is done on their end. Could be today or tomorrow.
